name       : haskell-temporary
version    : '1.3'
release    : 3
source     :
    - https://hackage.haskell.org/package/temporary-1.3/temporary-1.3.tar.gz : 8c442993694b5ffca823ce864af95bd2841fb5264ee511c61cf48cc71d879890
license    : BSD-3-Clause
component  : programming.haskell
summary    : This library just repackages the Cabal implementations of its own temporary file and folder functions so that you can use them without linking against Cabal or depending on it being installed.
description: |
    This library just repackages the Cabal implementations of its own temporary file and folder functions so that you can use them without linking against Cabal or depending on it being installed.
builddeps  :
    - haskell-cabal-install
    - haskell-exceptions-devel
    - haskell-random-devel
rundeps    :
    - devel:
        - haskell-exceptions-devel
        - haskell-random-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
