name       : haskell-temporary
version    : 1.2.0.4
release    : 1
source     :
    - http://hackage.haskell.org/package/temporary-1.2.0.4/temporary-1.2.0.4.tar.gz : 51e713804246404df8a728919a2e7d1994f8cfda42cfa7a74ea65d8b7d206762
license    : BSD-3-Clause
component  : programming.haskell
summary    : This library just repackages the Cabal implementations of its own temporary file and folder functions so that you can use them without linking against Cabal or depending on it being installed.
description: |
    This library just repackages the Cabal implementations of its own temporary file and folder functions so that you can use them without linking against Cabal or depending on it being installed.
builddeps  :
    - haskell-cabal-install
    - haskell-exceptions
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
